name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (format: vMAJOR.MINOR or vMAJOR.MINOR.PATCH, e.g., v1.0 or v1.0.0)'
        required: true

jobs:
  create_release_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Validate Version Format
        run: |
          VERSION_PATTERN='^v[0-9]+\.[0-9]+(\.[0-9]+)?$'
          if [[ ! "${{ github.event.inputs.release_version }}" =~ $VERSION_PATTERN ]]; then
            echo "Error: Release version '${{ github.event.inputs.release_version }}' does not match the required format 'vMAJOR.MINOR' or 'vMAJOR.MINOR.PATCH'."
            exit 1
          fi

      - name: Create Release Branch
        run: |
          RELEASE_BRANCH="release-${{ github.event.inputs.release_version }}"

          # Fetch the latest changes from origin
          git fetch origin

          # Check if release branch already exists
          if git ls-remote --heads origin $RELEASE_BRANCH; then
            echo "Release branch '$RELEASE_BRANCH' already exists. Exiting."
            exit 1
          fi

          # Create the release branch from develop
          git checkout origin/develop
          git checkout -b $RELEASE_BRANCH

          # Push the new release branch to the remote repository
          git push origin $RELEASE_BRANCH

          echo "Release branch '$RELEASE_BRANCH' created from 'develop' and pushed to origin."
